use LinhKienDienTu2
GO
CREATE TABLE NhanVien (
    MaNV NVARCHAR(30) CONSTRAINT PK_MaNV PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    SDT CHAR(11) CHECK (LEN(SDT) = 10) NOT NULL,
    NgayBDLamViec DATE CHECK (DATEDIFF(day, NgayBDLamViec, GETDATE()) >= 0) NOT NULL,
    NgaySinh DATE CHECK (DATEDIFF(year, NgaySinh, GETDATE()) >= 18),
    GioiTinh NVARCHAR(3),
    DiaChi NVARCHAR(100),
    Luong FLOAT CHECK (Luong >= 0) NOT NULL
);
GO
CREATE TABLE CaLamViec (
    MaCa NVARCHAR(30) CONSTRAINT PK_MaCa PRIMARY KEY,
    TenCa NVARCHAR(10) NOT NULL,
    Ngay DATE NOT NULL,
    ThoiGianBD TIME(0) NOT NULL,
    ThoiGianKT TIME(0) NOT NULL,
    CONSTRAINT CHK_ThoiGian CHECK (ThoiGianBD < ThoiGianKT)
);
GO
CREATE TABLE PhanCa (
    MaNhanVien NVARCHAR(30) CONSTRAINT FK_PhanCa_MaNhanVien FOREIGN KEY REFERENCES NhanVien(MaNV),
    MaCa NVARCHAR(30) CONSTRAINT FK_PhanCa_MaCa FOREIGN KEY REFERENCES CaLamViec(MaCa),
    CONSTRAINT PK_PhanCa PRIMARY KEY (MaNhanVien, MaCa),
	trangthai nvarchar(30)
);
GO
CREATE TABLE NhomLinhKien (
    MaNhom NVARCHAR(30) CONSTRAINT PK_MaNhom PRIMARY KEY,
    TenNhom NVARCHAR(50) NOT NULL,
    SoLuongLK INT CHECK (SoLuongLK >= 0) NOT NULL
);
GO
CREATE TABLE NhaCungCap (
    MaNCC NVARCHAR(30) CONSTRAINT PK_MaNCC PRIMARY KEY,
    SDT CHAR(11) CHECK (LEN(SDT) = 10) NOT NULL,
    TenNhaCungCap NVARCHAR(50) NOT NULL,
    DiaChi NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE LinhKien (
    MaLK NVARCHAR(30) CONSTRAINT PK_MaLK PRIMARY KEY,
    TenLK NVARCHAR(50) NOT NULL,
    GiaTien FLOAT CHECK (GiaTien > 0) NOT NULL,
    MoTa NVARCHAR(500) NOT NULL,
    TrangThai NVARCHAR(20) NOT NULL,

    SoLuong INT CHECK (SoLuong >= 0) NOT NULL,
    MaNhom NVARCHAR(30) CONSTRAINT FK_LinhKien_MaNhom FOREIGN KEY REFERENCES NhomLinhKien(MaNhom),
    MaNCC NVARCHAR(30) CONSTRAINT FK_LinhKien_MaNCC FOREIGN KEY REFERENCES NhaCungCap(MaNCC),
   AnhLK VARBINARY(MAX)
);
GO
CREATE TABLE KhachHang (
    MaKH NVARCHAR(30) CONSTRAINT PK_MaKH PRIMARY KEY,
    HoTen NVARCHAR(50) NOT NULL,
    SDT CHAR(11) CHECK (LEN(SDT) = 10) NOT NULL,
    Email NVARCHAR(50),
    DiaChi NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE HoaDon (
    MaHD NVARCHAR(30) CONSTRAINT PK_MaHD PRIMARY KEY,
    NgayXuat DATE CHECK (DATEDIFF(day, NgayXuat, GETDATE()) >= 0) NOT NULL,
    TongGiaTri FLOAT CHECK (TongGiaTri > 0) NOT NULL,
    MaKH NVARCHAR(30) CONSTRAINT FK_HoaDon_MaKH FOREIGN KEY REFERENCES KhachHang(MaKH),
    MaNV NVARCHAR(30) CONSTRAINT FK_HoaDon_MaNV FOREIGN KEY REFERENCES NhanVien(MaNV)
);
GO
CREATE TABLE ChiTietHD (
    MaLK NVARCHAR(30) CONSTRAINT FK_ChiTietHD_MaLK FOREIGN KEY REFERENCES LinhKien(MaLK),
    MaHD NVARCHAR(30) CONSTRAINT FK_ChiTietHD_MaHD FOREIGN KEY REFERENCES HoaDon(MaHD),
    SoLuong INT CHECK (SoLuong > 0) NOT NULL,
    DonGia FLOAT CHECK (DonGia > 0) NOT NULL,
    TongTien FLOAT CHECK (TongTien > 0) NOT NULL,
    CONSTRAINT PK_ChiTietHD PRIMARY KEY (MaLK, MaHD)
);
GO
CREATE TABLE DonNhapHang (
    MaDonNhap NVARCHAR(30) CONSTRAINT PK_MaDonNhap PRIMARY KEY,
    NgayNhap DATE CHECK (DATEDIFF(day, NgayNhap, GETDATE()) >= 0) NOT NULL,
    MaNCC NVARCHAR(30) CONSTRAINT FK_DonNhapHang_MaNCC FOREIGN KEY REFERENCES NhaCungCap(MaNCC) NOT NULL,
    GiaTriDonNhap FLOAT CHECK (GiaTriDonNhap > 0) NOT NULL
);
GO
CREATE TABLE NhapHang (
    MaLK NVARCHAR(30) CONSTRAINT FK_NhapHang_MaLK FOREIGN KEY REFERENCES LinhKien(MaLK),
    MaDonNhap NVARCHAR(30) CONSTRAINT FK_NhapHang_MaDonNhap FOREIGN KEY REFERENCES DonNhapHang(MaDonNhap),
    SoLuong INT CHECK (SoLuong > 0),
    DonGia FLOAT CHECK (DonGia > 0),
    TongTien FLOAT CHECK (TongTien > 0),
    CONSTRAINT PK_NhapHang PRIMARY KEY (MaLK, MaDonNhap)
);
